Repository elementary/code, pull requests merged in 2021-04, with the labels that each got.

#992 Fix regression due to c35a306f03e3ddef5c2d3c8dff4e69caaa78c667
  src/Widgets/Sidebar.vala
Labels: Priority: High, regression

#993 Document: changed message () to debug ()
  src/Services/Document.vala
Labels: Bitesize

#995 Remove Zeitgeist dep
  debian/control
Labels: Bitesize

#998 Update POTFILES
  po/POTFILES
Labels: Bitesize, i18n

#1002 NewBranchDialog: update primary text
  src/Dialogs/NewBranchDialog.vala
Labels: Bitesize

#1006 FolderManager: Add accel to find in project and rename find in folder
  src/FolderManager/FolderItem.vala
  src/FolderManager/ProjectFolderItem.vala
Labels: Bitesize

#1003 ProjectFolderItem: Show accel for new branch
  src/FolderManager/ProjectFolderItem.vala
Labels: Bitesize

#1014 GitManager: debug on error
  src/Services/GitManager.vala
Labels: Bitesize
