Repository elementary/code, pull requests merged in 2021-11, with the labels that each got.

#806 Removing toggling of terminal button visibility for #761
  data/io.elementary.code.appdata.xml.in
  plugins/terminal/terminal.vala
  src/MainWindow.vala
Labels: Needs Design, Conflicts with Master

#1128 GlobalSearchDialog: set active_window as transient parent
  src/Dialogs/GlobalSearchDialog.vala
  src/FolderManager/ProjectFolderItem.vala
Labels: Bitesize

#1135 Document: Set Filechooser Dialog as Transient for Main Window
  src/Services/Document.vala
Labels: Bitesize

#1131 Release 6.1.0
  data/io.elementary.code.appdata.xml.in
  meson.build
Labels: Release
