Repository elementary/code, pull requests merged in 2021-07, with the labels that each got.

#1078 Release 6.0.0
  data/io.elementary.code.appdata.xml.in
  data/screenshot-dark.png
  data/screenshot.png
  meson.build
Labels: Release

#1083 POTFILES: Add ChooseProjectButton.vala
  po/POTFILES
Labels: Bitesize

#1086 POTFILES: Add Markdown plugin
  po/plugins/POTFILES
Labels: Bitesize, i18n

#1088 README: bump granite dep
  README.md
Labels: Bitesize
