Repository elementary/code, pull requests merged in 2022-04, with the labels that each got.

#1160 Include hyphen and underscore in word to match
  plugins/word-completion/completion-provider.vala
  plugins/word-completion/engine.vala
  plugins/word-completion/plugin.vala
Labels: Status: Blocked

#1182 SearchBar: Make the search count translatable
  src/Widgets/SearchBar.vala
Labels: Bitesize, i18n

#1181 Release 6.2.0
  data/io.elementary.code.appdata.xml.in
  meson.build
Labels: Release
