Repository elementary/code, pull requests merged in 2023-01, with the labels that each got.

#1238 Do not add duplicate project
  src/Services/GitManager.vala
Labels: Bitesize

#1240 PluginManager: Remove unused hooks
  src/Services/PluginManager.vala
Labels: Bitesize

#1247 Release 7.0.0
  data/code.metainfo.xml.in
  meson.build
Labels: Release

#1254 Ensure active project at startup (include non-git folders)
  src/FolderManager/FileView.vala
  src/FolderManager/ProjectFolderItem.vala
  src/Services/GitManager.vala
Labels: Priority: High, regression
